In [1]:
import numpy as np

In [22]:
a=np.random.randn(10)

In [21]:
b=np.random.randn(10)

In [23]:
a-b

array([ 0.18394407,  1.20463588, -0.53120065, -0.84817174,  2.32792551,
       -0.63114406,  0.0472507 , -0.93190951,  0.63315604,  2.43973069])

In [24]:
a>1

array([False, False, False, False,  True, False, False, False,  True,
        True])

In [25]:
a[a>1]

array([1.34458194, 1.0063169 , 1.97418666])