In [3]:
import numpy as np
ar=np.array([4,5,7,1,3,9,3,11])
ar

array([ 4,  5,  7,  1,  3,  9,  3, 11])

In [4]:
ind=[4,6,0,3]
ar[ind]

array([3, 3, 4, 1])

In [5]:
ar.put(ind,1)
ar

array([ 1,  5,  7,  1,  1,  9,  1, 11])

In [6]:
ar.put(ind,[12,55,66,22])
ar

array([66,  5,  7, 22, 12,  9, 55, 11])

In [19]:
t=np.random.randn(3,4)
ix=np.array([2,1,0])
inx=np.array([2,0,2,1,0])
t

array([[ 0.33979178, -0.67679672,  0.69046732, -0.74080721],
       [-0.34102117, -0.01542453,  1.59959525,  1.48177525],
       [-1.13362923, -0.6240529 , -0.94796091,  0.41521835]])

In [20]:
t.take(ix,axis=1)

array([[ 0.69046732, -0.67679672,  0.33979178],
       [ 1.59959525, -0.01542453, -0.34102117],
       [-0.94796091, -0.6240529 , -1.13362923]])

In [21]:
t.take(inx,axis=0)

array([[-1.13362923, -0.6240529 , -0.94796091,  0.41521835],
       [ 0.33979178, -0.67679672,  0.69046732, -0.74080721],
       [-1.13362923, -0.6240529 , -0.94796091,  0.41521835],
       [-0.34102117, -0.01542453,  1.59959525,  1.48177525],
       [ 0.33979178, -0.67679672,  0.69046732, -0.74080721]])

In [10]:
b=np.arange(18).reshape(2,3,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [11]:
np.ndim(b)

3

In [12]:
np.swapaxes(b,0,1)

array([[[ 0,  1,  2],
        [ 9, 10, 11]],

       [[ 3,  4,  5],
        [12, 13, 14]],

       [[ 6,  7,  8],
        [15, 16, 17]]])

In [13]:
np.swapaxes(b,0,2)

array([[[ 0,  9],
        [ 3, 12],
        [ 6, 15]],

       [[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]]])

In [14]:
np.swapaxes(b,2,0)

array([[[ 0,  9],
        [ 3, 12],
        [ 6, 15]],

       [[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]]])

In [15]:
np.swapaxes(b,0,2)

array([[[ 0,  9],
        [ 3, 12],
        [ 6, 15]],

       [[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]]])

In [16]:
c=np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
c.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])