In [2]:
import numpy as np
x=np.array([1.0067,4.54545,5.8666])
rem,whole_part=np.modf(x)

In [8]:
rem,whole_part

(array([0.0067 , 0.54545, 0.8666 ]), array([1., 4., 5.]))

In [14]:
y=np.array([-1,3,-6,5,0])
np.sign(y)

array([-1,  1, -1,  1,  0])

In [9]:
yy=np.array([3.0014,65.4545454,56.1133444,4.900087])

In [10]:
np.ceil(yy)

array([ 4., 66., 57.,  5.])

In [11]:
np.floor(yy)

array([ 3., 65., 56.,  4.])

In [16]:
xx=np.array([2.67,7.876,5.01,23])

In [17]:
np.rint(xx)

array([ 3.,  8.,  5., 23.])

In [18]:
np.add(xx,yy)

array([ 5.6714   , 73.3305454, 61.1233444, 27.900087 ])