In [2]:
import numpy as np
import pandas as pd
import csv

In [22]:
with open('mydata.txt', 'w') as f:
    writer = csv.writer(f,delimiter='|')
    writer.writerow(('one', 'two', 'three'))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))

In [23]:
with open("mydata.txt","r") as r:
    text=r.read()
    print(text)

one|two|three

1|2|3

4|5|6

7|8|9




In [2]:
x=np.array([1,4,5,3])
y=np.array([2,3,2,42])

In [3]:
np.save('arrayx.npy',x)

In [4]:
load=np.load('arrayx.npy')
load

array([1, 4, 5, 3])

In [5]:
np.savez('arxy.npz',x=x,y=y)

In [6]:
lod=np.load('arxy.npz')

In [7]:
lod

In [8]:
lod['y']  

array([ 2,  3,  2, 42])

In [9]:
np.savez_compressed("arxy_compressed.npz",x=x,y=y)

In [11]:
lod=np.load('arxy_compressed.npz')

In [13]:
lod['x']

array([1, 4, 5, 3])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [34]:
l=pd.read_csv('yob1880.txt',names=['Names','F','Sno'])
l.head()

Names  F   Sno
0       Mary  F  7065
1       Anna  F  2604
2       Emma  F  2003
3  Elizabeth  F  1939
4     Minnie  F  1746

In [50]:
dic={'asif':['b17101021','21121997']}
u=pd.read_csv('untitled.txt',sep='\s+',na_values=dic)
u

name  is  asif
0     dob  is   NaN
1  seatno  is   NaN

In [33]:
u=pd.read_csv('untitled.txt',index_col=['key1','key2'])
u.columns.name='CLOUMNS'
u

CLOUMNS    value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [63]:
r=pd.read_csv('train.csv',nrows=200)
r
#r.nsmallest(5, ['int_memory']) 

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0              842     0          2.2         0   1       0           7   
1             1021     1          0.5         1   0       1          53   
2              563     1          0.5         1   2       1          41   
3              615     1          2.5         0   0       0          10   
4             1821     1          1.2         0  13       1          44   
5             1859     0          0.5         1   3       0          22   
6             1821     0          1.7         0   4       1          10   
7             1954     0          0.5         1   0       0          24   
8             1445     1          0.5         0   0       0          53   
9              509     1          0.6         1   2       1           9   
10             769     1          2.9         1   0       0           9   
11            1520     1          2.2         0   5       1          33   
12            1815     0          2.8         0   2       0          33   
13             803     1          2.1         0   7       0          17   
14            1866     0          0.5         0  13       1          52   
15             775     0          1.0         0   3       0          46   
16             838     0          0.5         0   1       1          13   
17             595     0          0.9         1   7       1          23   
18            1131     1          0.5         1  11       0          49   
19             682     1          0.5         0   4       0          19   
20             772     0          1.1         1  12       0          39   
21            1709     1          2.1         0   1       0          13   
22            1949     0          2.6         1   4       0          47   
23            1602     1          2.8         1   4       1          38   
24             503     0          1.2         1   5       1           8   
25             961     1          1.4         1   0       1          57   
26             519     1          1.6         1   7       1          51   
27             956     0          0.5         0   1       1          41   
28            1453     0          1.6         1  12       1          52   
29             851     0          0.5         0   3       0          21   
..             ...   ...          ...       ...  ..     ...         ...   
170           1270     1          0.6         1   2       1          32   
171           1854     0          3.0         0   2       1           8   
172            625     1          1.2         1   5       1          10   
173           1577     0          0.5         1   0       1          42   
174            534     0          0.5         1   0       1          16   
175            946     0          1.7         1   8       1          25   
176            685     0          0.5         0   2       0          29   
177           1949     0          1.3         1   0       0          23   
178            947     0          0.8         1   0       1          22   
179            801     1          2.2         1   2       0          63   
180            703     1          2.7         0  12       1          30   
181           1165     1          2.4         0  11       0          41   
182           1082     0          0.8         0   0       0          38   
183            959     1          2.6         1  15       0          20   
184           1502     1          1.2         0   0       0          54   
185           1380     1          2.1         1   1       1           4   
186           1266     0          0.5         0   0       1           5   
187           1934     1          2.6         1   0       1          46   
188           1905     1          0.5         0   3       1           6   
189           1831     0          1.4         1   2       0          43   
190            596     0          1.4         0   8       0          46   
191           1562     1      

In [95]:
c=pd.read_csv('train.csv',chunksize=200)
chunklist=[]

for chunk in c:
    chunklist.append(chunk)
chunklist[2]

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
400           1266     0          1.9         1   0       1           7   
401           1042     0          2.7         1  16       1          50   
402           1479     0          0.5         0   8       0          19   
403           1476     1          1.2         1   0       1          55   
404           1552     1          2.2         0   6       1          13   
405           1454     1          0.5         1   1       0          34   
406           1007     0          2.0         0   0       0          45   
407            652     1          2.4         1   9       1          17   
408           1504     0          1.5         0  12       1          34   
409           1726     1          0.9         1   2       0          51   
410           1029     1          1.9         1   5       1           5   
411           1582     0          2.8         0   2       1          44   
412           1478     1          0.8         1  12       0          48   
413           1178     1          1.3         0   0       0          49   
414            707     0          2.1         1   2       0          25   
415            755     1          2.8         0   5       1          51   
416            912     1          2.0         0   1       0          54   
417            651     1          0.8         1   2       1          63   
418           1483     0          2.1         0   1       1          54   
419            914     1          0.9         0   2       0           4   
420           1456     1          0.5         1   7       0           7   
421           1178     0          2.2         1   6       0          57   
422           1503     1          0.7         0  10       1          43   
423           1681     1          2.5         0   2       0          11   
424            715     0          2.3         1   4       0          48   
425           1876     0          2.8         1   3       1          56   
426           1190     1          2.2         1   9       0          47   
427           1755     1          1.3         0   0       1          24   
428           1197     0          1.3         0   3       1          20   
429           1048     1          0.9         0  10       1          28   
..             ...   ...          ...       ...  ..     ...         ...   
570           1572     1          0.8         1   7       1           8   
571           1627     0          0.9         1   9       1          32   
572           1701     1          0.5         0  13       1          46   
573           1900     1          0.5         1   0       1          55   
574           1974     0          1.0         0   4       0          24   
575           1197     1          0.5         1   9       0          20   
576            587     1          2.3         1   4       0           6   
577            934     0          1.1         0   7       0          24   
578           1195     0          2.0         1   1       1          23   
579           1853     1          1.0         0   2       0          23   
580           1164     0          1.0         0   4       1          19   
581           1512     1          0.5         0   8       1          18   
582           1232     0          2.9         1   1       1          24   
583           1813     1          0.6         1   0       1           5   
584            946     1          2.6         1  17       0           5   
585            739     1          2.3         1   2       1          58   
586            704     1          2.7         0   8       1          29   
587           1663     1          0.5         0   0       0          40   
588           1966     1          1.4         1   2       0          40   
589           1219     0          1.0         1   0       0          17   
590            612     1          0.7         0   6       0          35   
591           1658     1      