In [1]:
import numpy as np

In [2]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.dot(x,y)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [5]:
np.transpose(y)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
np.diagonal(x)

array([1, 5, 9])

In [7]:
np.diag(y)

array([1, 5, 9])

In [8]:
np.linalg.det(x)

6.66133814775094e-16

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.dot(x,np.ones(3))

array([ 6., 15., 24.])