In [1]:
import numpy as np

# Statistical

In [2]:
b=np.array([2,4,5,3,])

In [3]:
a=b<3
a

array([ True, False, False, False])

In [4]:
a.sum()

1

In [5]:
a.all()

False

In [6]:
a.any()

True

In [7]:
b.cumsum()

array([ 2,  6, 11, 14], dtype=int32)

In [8]:
b.sort()
b

array([2, 3, 4, 5])

In [9]:
np.unique(b)

array([2, 3, 4, 5])

In [10]:
a=np.arange(-10,10,4)
a

array([-10,  -6,  -2,   2,   6])

In [11]:
x=np.array([[1,3,4],[4,5,5]])
x

array([[1, 3, 4],
       [4, 5, 5]])

In [12]:
x.mean()

3.6666666666666665

In [13]:
x.mean(axis=0)

array([2.5, 4. , 4.5])

In [14]:
x.mean(axis=1)

array([2.66666667, 4.66666667])

In [15]:
x.sum()

22

In [16]:
x.sum(axis=0)

array([5, 8, 9])

In [2]:
d=np.array([221,6,7,9,5,8,990])
c=np.array([290,4,5,3,100,56,45])

In [18]:
c.argmin()

3

In [19]:
c.max()

290

In [3]:
ar=np.arange(1,100)

In [6]:
(ar<50).sum()

49

In [22]:
(ar<50).any()

True

In [23]:
(ar<50).all()

False

In [24]:
#-------------------------------------------------

In [25]:
bl=np.array([[11,4,15],[14,6,1],[9,12,10]])
bl

array([[11,  4, 15],
       [14,  6,  1],
       [ 9, 12, 10]])

In [26]:
bl.sort(1)
bl

array([[ 4, 11, 15],
       [ 1,  6, 14],
       [ 9, 10, 12]])

In [27]:
bl.sort(0)
bl

array([[ 1,  6, 12],
       [ 4, 10, 14],
       [ 9, 11, 15]])

In [28]:
bl.sort()
bl

array([[ 1,  6, 12],
       [ 4, 10, 14],
       [ 9, 11, 15]])

In [29]:
l=np.arange(16).reshape(4,4)
l

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
np.ndim(l)

2

In [31]:
l.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
#copy of the data
l.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [33]:
l[::-2,::2]

array([[12, 14],
       [ 4,  6]])

In [34]:
l[::-2,::-2]

array([[15, 13],
       [ 7,  5]])

In [35]:
l[::2, ::-2]

array([[ 3,  1],
       [11,  9]])

# Concatenating 

In [8]:
p=np.arange(9).reshape(3,3)
q=np.array([[12,5,1],[9,10,8],[8,2,8]])
r=np.arange(12).reshape(6,2)

In [9]:
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
q

array([[12,  5,  1],
       [ 9, 10,  8],
       [ 8,  2,  8]])

In [11]:
#np.concatenate([p,q])
np.concatenate([p,q])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [12,  5,  1],
       [ 9, 10,  8],
       [ 8,  2,  8]])

In [40]:
np.concatenate([p,q],axis=1)

array([[ 0,  1,  2, 12,  5,  1],
       [ 3,  4,  5,  9, 10,  8],
       [ 6,  7,  8,  8,  2,  8]])

In [41]:
np.vstack((p,q))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [12,  5,  1],
       [ 9, 10,  8],
       [ 8,  2,  8]])

In [42]:
np.hstack((p,q))

array([[ 0,  1,  2, 12,  5,  1],
       [ 3,  4,  5,  9, 10,  8],
       [ 6,  7,  8,  8,  2,  8]])

In [43]:
np.column_stack((p,q))

array([[ 0,  1,  2, 12,  5,  1],
       [ 3,  4,  5,  9, 10,  8],
       [ 6,  7,  8,  8,  2,  8]])

In [44]:
np.r_[p,q]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [12,  5,  1],
       [ 9, 10,  8],
       [ 8,  2,  8]])

In [45]:
np.c_[p,q]

array([[ 0,  1,  2, 12,  5,  1],
       [ 3,  4,  5,  9, 10,  8],
       [ 6,  7,  8,  8,  2,  8]])

In [46]:
np.c_[1:6,-11:-6]

array([[  1, -11],
       [  2, -10],
       [  3,  -9],
       [  4,  -8],
       [  5,  -7]])

In [47]:
r

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [62]:
np.c_[np.r_[p,q],r]

array([[ 0,  1,  2,  0,  1],
       [ 3,  4,  5,  2,  3],
       [ 6,  7,  8,  4,  5],
       [12,  5,  1,  6,  7],
       [ 9, 10,  8,  8,  9],
       [ 8,  2,  8, 10, 11]])

In [49]:
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
q

array([[12,  5,  1],
       [ 9, 10,  8],
       [ 8,  2,  8]])

In [51]:
np.dstack((p,q))

array([[[ 0, 12],
        [ 1,  5],
        [ 2,  1]],

       [[ 3,  9],
        [ 4, 10],
        [ 5,  8]],

       [[ 6,  8],
        [ 7,  2],
        [ 8,  8]]])

# Spliting

In [13]:
ary=np.arange(50).reshape(10,5)
ary

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [14]:
first, second, third = np.split(ary, [2,5])

In [54]:
first

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
second

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
third

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

# Repeating

In [57]:
first.repeat(2,axis=1)

array([[0, 0, 1, 1, 2, 2, 3, 3, 4, 4],
       [5, 5, 6, 6, 7, 7, 8, 8, 9, 9]])

In [58]:
second.repeat(2,axis=0)

array([[10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [20, 21, 22, 23, 24]])

In [20]:
first.repeat([4,2],axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [80]:
arr=np.random.randn(2,2)
arr

array([[ 1.03534726, -0.3625468 ],
       [ 0.55532835, -0.94724789]])

In [85]:
first.repeat([2,3],axis=1)

ValueError: operands could not be broadcast together with shape (5,) (2,)

In [86]:
p

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
np.tile(p,4)

array([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [22]:
np.tile(p,[2,4])

array([[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8],
       [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8, 6, 7, 8, 6, 7, 8]])

In [23]:
ax=np.arange(10).reshape(5,2)
ax

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
s=np.arange(128).reshape(2,8,8)
s

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]]])

In [12]:
np.split(s,[4,6],axis=1)

[array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29, 30, 31]],
 
        [[64, 65, 66, 67, 68, 69, 70, 71],
         [72, 73, 74, 75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84, 85, 86, 87],
         [88, 89, 90, 91, 92, 93, 94, 95]]]),
 array([[[ 32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47]],
 
        [[ 96,  97,  98,  99, 100, 101, 102, 103],
         [104, 105, 106, 107, 108, 109, 110, 111]]]),
 array([[[ 48,  49,  50,  51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60,  61,  62,  63]],
 
        [[112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127]]])]