In [2]:
import numpy as np

In [3]:
a=np.random.randn(5,5)

In [4]:
a

array([[ 0.46458275, -0.95585024, -0.49078645,  0.6782687 , -0.75792177],
       [-0.52767444, -0.4110216 , -0.99491724, -0.40714787,  0.67296783],
       [ 0.38503624,  0.73843064, -0.04748321,  0.41657028, -0.481713  ],
       [ 0.51325792, -0.62977282,  1.19688295, -1.20297362, -1.19024624],
       [ 0.75933316, -0.39499525,  0.10932685,  0.42038381,  1.20535453]])

In [5]:
x=np.array(a,dtype='int')

In [6]:
x

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  1, -1, -1],
       [ 0,  0,  0,  0,  1]])

In [7]:
y=a.astype(int)

In [8]:
y

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  1, -1, -1],
       [ 0,  0,  0,  0,  1]])

In [9]:
b=abs(x)
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 1]
 [0 0 0 0 1]]


In [10]:
b[0][2]

0

In [11]:
b[]
print(b)

SyntaxError: invalid syntax (<ipython-input-11-5bb138f50328>, line 1)

In [12]:
seq=[1,2,4,6,8,29,5,3,0,6,2,5,7,1,5,3,2,7,8,99]

In [13]:
seq[::3]

[1, 6, 5, 6, 7, 3, 8]

In [14]:
seq.count(2)

3

In [16]:
seq.sort()

In [17]:
seq

[0, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 5, 6, 6, 7, 7, 8, 8, 29, 99]

In [ ]:
seq[::-1]

In [ ]:
print(l)

In [19]:
li=[1,3,2,4,2]

In [20]:
li.sort(reverse=True)

In [21]:
li

[4, 3, 2, 2, 1]

In [ ]:
seq1 = ['foo', 'bar', 'baz']
seq2 = ['one', 'two', 'three']
zipped = zip(seq1, seq2)

In [ ]:
list(zipped)

In [ ]:
a=1
b=2
c=4
print(f'these are the values of a={a},b={b},c={c}')

In [ ]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

In [ ]:
a.update(b)

In [ ]:
a

In [ ]:
b

In [ ]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

In [ ]:
a|b

# Strinping

In [ ]:
import re
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?@-]', '', value)
        value = value.title()
        result.append(value)
    return result

states = [' Alabama ', 'Georgia!', 'Georgia--', 'georgia@@', 'FlOrIda','south carolina##', 'West virginia?']
clean_strings(states)

In [ ]:
import re
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?@-]', '', value)
        value = value.title()
        result.append(value)
    return result

states = [' Alabama ', 'Georgia!', 'Georgia--', 'georgia@@', 'FlOrIda','south carolina##', 'West virginia?']
clean_strings(states)

In [ ]:
#s="Asif      Ahmed    Jamil     Ahmed"

s='my#@name   is!@#    Asif aHMED'
st=re.sub('[!@#$%^&,*()_+]',' ',s)
#st=st.strip()
st=" ".join(st.split())


In [ ]:
print(st)

In [ ]:
name=input()
#name="Asif ##     Ahmed##    Jamil     Ahmed"
name=re.sub('[#]','',name)
name=name.strip()
name=" ".join(name.split())
print(name)

In [ ]:
def remove_punctuation(value):
    s=re.sub('[!?#@-]', '', value)
    return s.strip()


states = [' Alabama ', 'Georgia!', 'Georgia--', 'georgia@@', 'FlOrIda','south carolina##', 'West virginia?']
for x in map(remove_punctuation, states):
    print(x)

In [ ]:
list1=('egg',1000),('milk',1034),('butter',500),('peach',200)
list1=sorted(list1,key = lambda x:x[1])
print(list1)

In [ ]:
type(list1)

In [ ]:
import pprint as pp
l1=[{'make':'car','model':'lush','year':2000},{'make':'bike','model':'stylish','year':1990},{'make':'truck','model':'metal','year':1995}]
l1=sorted(l1,key=lambda x:x['year'])
#l2=l1.sort(key=lambda x:x['year'])
#print(l2)
pp.pprint(l1)

In [ ]:
type(l1)

In [ ]:
l=[1,2,3,4,56,6]
k=list(filter(lambda x:x%2==0,l))

In [ ]:
k

In [ ]:
l=[1,2,3,4,56,6]
k=list(map(lambda x:x*2,l))

In [ ]:
k

In [ ]:
wbf4=lambda s,w:s.split()[s.split().index(w)-1] if w in s else None
sentence='my name is anything else'
n=input("enter awword")
print(wbf4(sentence,n))