In [1]:
import numpy as np

In [2]:
arr=np.arange(25).reshape(5,5)

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
arr[1,:2]

array([5, 6])

In [5]:
arr[1:-1,1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [6]:
arr[::,1:-1]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [7]:
arr[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [8]:
arr[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [9]:
a=np.arange(25).reshape(5,5)

In [10]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
a[::2,::2]=8

In [12]:
a

array([[ 8,  1,  8,  3,  8],
       [ 5,  6,  7,  8,  9],
       [ 8, 11,  8, 13,  8],
       [15, 16, 17, 18, 19],
       [ 8, 21,  8, 23,  8]])

In [13]:
a[0:0,0:0]=1

In [14]:
a

array([[ 8,  1,  8,  3,  8],
       [ 5,  6,  7,  8,  9],
       [ 8, 11,  8, 13,  8],
       [15, 16, 17, 18, 19],
       [ 8, 21,  8, 23,  8]])

In [15]:
a[::4]=1

In [16]:
a[::,:-1]

array([[ 1,  1,  1,  1],
       [ 5,  6,  7,  8],
       [ 8, 11,  8, 13],
       [15, 16, 17, 18],
       [ 1,  1,  1,  1]])

In [17]:
import numpy as np
x=np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
#x[[row,row,row,row,row][colmn,colmn,colmn,colmn]]
x[[1, 4, 1], [0, 3, 1]]

array([ 5, 23,  6])

In [19]:
x[[1, 3, 4, 2]][:, [0, 3, 1, 2]]

array([[ 5,  8,  6,  7],
       [15, 18, 16, 17],
       [20, 23, 21, 22],
       [10, 13, 11, 12]])

In [20]:
x[[3,4,1]][:,[0,2,4,3]]

array([[15, 17, 19, 18],
       [20, 22, 24, 23],
       [ 5,  7,  9,  8]])

In [21]:
y=np.arange(25).reshape(5,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
y.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [23]:
s=np.arange(18).reshape(2,3,3)
s

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [24]:
s.transpose((0,1,2))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [25]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [26]:
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [27]:
# [1 2] [11 12]
# [3 4] [13 14]

In [28]:
# [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]